# Generated by Django 3.1.7 on 2021-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northernlight', '0003_auto_20210327_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='anomaly',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
    ]
