# Generated by Django 3.1.7 on 2021-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northernlight', '0004_userdata_anomaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontrol',
            name='port1',
        ),
        migrations.RemoveField(
            model_name='usercontrol',
            name='port2',
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='name',
            field=models.TextField(default='Unnamed'),
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='port',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='condition',
            field=models.PositiveIntegerField(default=666),
        ),
    ]
