# Generated by Django 3.1.7 on 2021-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northernlight', '0005_auto_20210329_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontrol',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
